name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  library:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test